export const categoryFilters: Record<string, string[]> = {
  Macbook: ["macbook", "apple"],
  Herní: ["herní", "gaming", "rtx", "predator", "legion", "rog", "tuf"],
  Kancelářské: ["kancelář", "office", "vostro", "probook", "business"],
  Profesionální: [
    "profesionální",
    "workstation",
    "thinkpad",
    "latitude",
    "precision",
    "expertbook",
  ],
  Stylové: [
    "stylový",
    "slim",
    "zenbook",
    "vivobook",
    "spectre",
    "enve",
    "yoga",
    "swift",
  ],
  Základní: ["základní", "student", "ideapad", "aspire", "modern"],
  Dotykové: ["dotykový", "touch", "flip", "x360"],
  "Na splátky": [],
  "VR Ready": ["vr ready", "vr-ready"],
  "IRIS Graphics": ["iris"],
  "Brašny, batohy": ["brašna", "batoh", "pouzdro", "case", "sleeve"],
  Příslušenství: ["myš", "klávesnice", "hub", "redukce", "dokovací", "adaptér"],
};